send:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: homeduino
          filter:
            - integration: homeduino
              model: transceiver
    command:
      required: true
      example: "RF send 4 3 453 1992 88 9228 0 0 0 0 01020102020201020101010101010102010101010202010202020202010102010102020203"
      selector:
        text:
rf_send:
  fields:
    protocol:
      required: true
      example: switch1
      selector:
        text:
    id:
      description: 
      required: true
      example: 5
      selector:
        number:
          min: 0
          mode: box
    unit:
      required: true
      example: 12
      selector:
        number:
          min: 0
          mode: box
    state:
      required: true
      example: true
      selector:
        boolean:
    all:
      required: true
      example: true
      selector:
        boolean:
    repeats:
      required: false
      example: 7
      selector:
        number:
          min: 1
          mode: box
raw_rf_send:
  fields:
    command:
      required: true
      example: "453 1992 88 9228 0 0 0 0 01020102020201020101010101010102010101010202010202020202010102010102020203"
      selector:
        text:
    repeats:
      required: false
      example: 7
      selector:
        number:
          min: 1
          mode: box
